package extensionsconst

// References : https://t.ly/4dWf
//
//goland:noinspection ALL
const (
	AllFiles                string = "*.*"
	DotAny                  string = ".*"
	AllExtensionFilterStart string = "*."
	DotPdf                  string = ".pdf"
	DotJpg                  string = ".jpg"
	DotDoc                  string = ".doc"
	DotTxt                  string = ".txt"
	DotJson                 string = ".json"
	DotYaml                 string = ".yaml"
	DotConf                 string = ".conf"
	DotDb                   string = ".db"
	DotBak                  string = ".bak"
	DotBack                 string = ".back"
	DotFile                 string = ".file"
	DotBin                  string = ".bin"
	DotIni                  string = ".ini"
	DotSh                   string = ".sh"
	DotBash                 string = ".bash"
	DotInstruction          string = ".instruction"
	DotPkg                  string = ".pkg"
	DotPackage              string = ".package"
	DotCache                string = ".cache"
	DotSql                  string = ".sql"
	DotImap                 string = ".imap"
	DotXml                  string = ".xml"
	DotPs                   string = ".ps"
	DotPy                   string = ".py"
	DotPhp                  string = ".php"
	DotO                    string = ".o"
	DotLog                  string = ".log"
	DotLock                 string = ".lock"
	DotIso                  string = ".iso"
	DotZip                  string = ".zip"
	DotTar                  string = ".tar"
	DotTarGz                string = ".tar.gz"
	DotTarBz                string = ".tar.bz"
	Dot7z                   string = ".7z"
	DotH                    string = ".h"
	DotDiff                 string = ".diff"
	DotDeb                  string = ".deb"
	DotCpp                  string = ".cpp"
	DotBz2                  string = ".bz2"
	DotRpm                  string = ".rpm"
	DotS                    string = ".s" // assembly source file
	DotPem                  string = ".pem"
	DotKey                  string = ".key"
)
