package extensionsconst

// References : https://t.ly/4dWf
//
//goland:noinspection ALL
const (
	Pdf         string = "pdf"
	Jpg         string = "jpg"
	Doc         string = "doc"
	Txt         string = "txt"
	Json        string = "json"
	Yaml        string = "yaml"
	Conf        string = "conf"
	Db          string = "db"
	Bak         string = "bak"
	Back        string = "back"
	File        string = "file"
	Bin         string = "bin"
	Ini         string = "ini"
	Sh          string = "sh"
	Bash        string = "bash"
	Instruction string = "instruction"
	Pkg         string = "pkg"
	Package     string = "package"
	Cache       string = "cache"
	Sql         string = "sql"
	Imap        string = "imap"
	Xml         string = "xml"
	Ps          string = "ps"
	Py          string = "py"
	Php         string = "php"
	O           string = "o"
	Log         string = "log"
	Lock        string = "lock"
	Iso         string = "iso"
	Zip         string = "zip"
	Tar         string = "tar"
	TarGz       string = "tar.gz"
	TarBz       string = "tar.bz"
	N7z         string = "7z"
	H           string = "h"
	Diff        string = "diff"
	Deb         string = "deb"
	Cpp         string = "cpp"
	Bz2         string = "bz2"
	Rpm         string = "rpm"
	S           string = "s" // assembly source file
	Pem         string = "pem"
	Key         string = "key"
	Backup      string = "backup"
	Ins         string = "ins"
)
